### PR TITLE
Added forget password using sqlite3 database and removed bugs while updating password.

### PR DESCRIPTION
**Pull request by Vedansh-777**
Forget password option for the user:
Screenshot 2023-06-13 at 11 24 18 AM

Checking Username in database to reset password :
Screenshot 2023-06-13 at 11 25 24 AM

If username not found in database :
Screenshot 2023-06-13 at 11 27 14 AM

Updating password :
Screenshot 2023-06-13 at 11 26 23 AM

### CODE REVIEW

**Comment by Vedansh-777** [comment]
@Pranjal360Agarwal I have changed little bit is it still showing error?

**Comment by Pranjal360Agarwal** [comment]
@Vedansh-777 now it is working fine.

**Comment by Pranjal360Agarwal** [comment]
@Vedansh-777 when on cloning the repo, this buffer file is giving error, hence the repo can't be cloned?

**Comment by Vedansh-777** [comment]
@Pranjal360Agarwal can you explain it in bit detail?

**Comment by Pranjal360Agarwal** [comment]
@Vedansh-777 refer to this PR, https://github.com/Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System/pull/188

and raise a new PR with the new file name asap, as of now , I am removing the labels since it is against the code of conduct

**Comment by Vedansh-777** [comment]
@Pranjal360Agarwal I've successfully cloned the repository files, and they are functioning perfectly.

1. 
Screenshot 2023-06-17 at 3 37 12 PM

2.
 Screenshot 2023-06-17 at 3 14 02 PM

3.
Screenshot 2023-06-17 at 3 16 01 PM

**Comment by Pranjal360Agarwal** [comment]
Have u ignored the two buffer files?
During cloning!!

**Comment by Vedansh-777** [comment]
No i haven't ignored any of the two buffer files during cloning.

**Comment by Vedansh-777** [comment]
Yes, I am using mac os that's why ig mine code is working fine..

**Comment by Pranjal360Agarwal** [comment]
@Anshika-Jain02 @Vedansh-777 Vedansh u need to look for the alternate file names and create a new PR so that a new contributor will not face any issue, but try to raise the PR asap, and I will add the label only then.

**Comment by Vedansh-777** [comment]
@Anshika-Jain02 https://github.com/Vedansh-777/ApnaBharat-Bus-Booking-Reservation-System.git clone this and let me know whether it is working, and if it's showing an error, share SS also. Because I don't have Windows OS.

**Comment by Pranjal360Agarwal** [comment]
@Vedansh-777 https://github.com/Vedansh-777/ApnaBharat-Bus-Booking-Reservation-System.git This clone is working fine, so raise this PR containing this, all features are working properly.

**Comment by Pranjal360Agarwal** [comment]
> @Pranjal360Agarwal sir, so should i close my PR #188 and create a new one after this issue is solved?

@Anshika-Jain02 Don't close your PR, let it be remain open.

**Comment by Pranjal360Agarwal** [comment]
@Anshika-Jain02 it is working fine, just check the folder that has been created and execute the main file, all features are working properly.

**Comment by Vedansh-777** [comment]
@Pranjal360Agarwal, if it is working fine, please also add labels again.

**Pull request merged**
