### PR TITLE
[GSSoC 23'] Successfully Added Dark Theme Button & Bug Resolve

### PR DESCRIPTION
**Pull request by HartzFrequency**
Hello, @Pranjal360Agarwal ! I've implemented a dark theme button for switching between tkinter themes. Additionally, I've fixed a bug and I'll provide more information about the changes in the following comment.

### CODE REVIEW

**Comment by HartzFrequency** [comment]
_Hi @Pranjal360Agarwal , here are the details of the changes made_ 

****BUG ENCOUNTERED**** 

If you previously encountered a situation where you could switch from the sign-in window to the main window without entering the correct username and password, that issue has been resolved. Now, if you close the sign-in window without providing the necessary credentials, the program will halt and further execution will be prevented.

BUG is resolved using the function 

    def Transition_LoginToMain():
        with open('Modules\\SignIn_Module\\SignIn_Check.txt', 'r') as file:
            content = file.read()
        value = bool(content)

        if not value:
            exit()
 
        with open('Modules\\SignIn_Module\\SignIn_Check.txt', 'w') as file2:
            file2.truncate(0)


**ABOUT THE THEME**

- Theme 1
  
image

- Theme 2

image

- Theme 3

image

**Comment by Pranjal360Agarwal** [comment]
great @HartzFrequency

**Comment by HartzFrequency** [comment]
hi @Pranjal360Agarwal, thanks for merging the PR, can you please assign labels to it, it will be so great of you!
Thank you @Pranjal360Agarwal

**Comment by gurjeetsinghvirdee** [comment]
@Pranjal360Agarwal Kindly add gssoc23 & pointa label on merged PRs

**Pull request merged**
