### PR TITLE
Features

### PR DESCRIPTION
**Pull request by Swap-Nova**
* Added a folder named ```Login System Architecture``` in a branch named <b>Features</b>
*  There are multiple windows included in this project, it is a simple way to create a login system.  
*  The users have to put their username and password before use, it will maintain the project's privacy and security.
* Various python components were used in this project  Frames, Labels, Entries, buttons, and Message Boxes.
* For a detailed explanation of the code you can read the documentation created inside the folder.

### CODE REVIEW

**Comment by Pranjal360Agarwal** [comment]
Looks Great!!


can you just send the video recording on how this project is working after adding your lines of code

**Comment by Pranjal360Agarwal** [comment]
On my whatsapp no:- 9451492673

**Comment by Swap-Nova** [comment]
Yeah sure. Will share it with you by today evening.

**Comment by Pranjal360Agarwal** [comment]
@Swap-Nova Just want to ask that when the user register or login, will the first page of my project be opened or not!!
that is , are your features are fully integrated with the existing project or not

**Comment by Swap-Nova** [comment]
@Pranjal360Agarwal Actually the project folder which I uploaded is not currently integrated with your existing project. 
It will open its own user register/login. 
But if you want to integrate it with yours we can use the same code functionalities in your existing project.

**Comment by Swap-Nova** [comment]
@Pranjal360Agarwal Actually the project folder which I uploaded is not currently integrated with your existing project.
It will open its own user register/login.
But if you want to integrate it with yours we can use the same code functionalities in my project folder and add it to your existing project.

**Comment by Pranjal360Agarwal** [comment]
@Swap-Nova  has done amazing work, above my expectations
**I will recommend & prefer this work at a great level, you will surely avail the benefits of your work**

**Comment by Swap-Nova** [comment]
Thank you so much @Pranjal360Agarwal

**Comment by Pranjal360Agarwal** [comment]
@Swap-Nova , try to integrate your feature at the start of this project, means when the user login/register , then clicks  a button then the first page of the project should be opened

**Comment by Pranjal360Agarwal** [comment]
Hope you can integrate in this project!!

**Comment by Swap-Nova** [comment]
Will do that for sure. Just need a couple of days, unforunfortunately stuck with my final exams.

**Comment by Swap-Nova** [comment]
Will do that for sure. Just need a couple of days, unfortunately, stuck with my final exams.

**Comment by Pranjal360Agarwal** [comment]
@Swap-Nova No issue, you can work on it accordingly.
I can totally understand the situation!!
But I appreciate your efforts for giving your precious time to this project!!

If possible, can you star the project!!

**Comment by Swap-Nova** [comment]
Yeah, sure no problem.

**Comment by Swap-Nova** [comment]
Regarding the Integration of the Login/Sign Up Page.... I will work on it and send you a PR soon.

**Pull request merged**
