### PR TITLE
modify login page

### PR DESCRIPTION
**Pull request by krishvsoni**

### CODE REVIEW

**Comment by Pranjal360Agarwal** [comment]
@krishvsoni please elaborate how exactly login page is improved

**Comment by krishvsoni** [comment]
> @krishvsoni please elaborate how exactly login page is improved

I changed the html/css/js and made the design more attractive

**Comment by Pranjal360Agarwal** [comment]
@krishvsoni I can't find any difference, provide some snapshots of the difference

**Comment by krishvsoni** [comment]
Screenshot (2)

**Comment by Pranjal360Agarwal** [comment]
@krishvsoni the login page looks cool, but there is no html file in the project as this project is entirely based using python

**Pull request closed without merging**
