### PR TITLE
Dropdown menu updated

### PR DESCRIPTION
**Pull request by arijitghosal03**
Included a drop down menu at the to and from sections of seat booking feature
Fixes issue #101

### CODE REVIEW

**Comment by Pranjal360Agarwal** [comment]
Have you updated the database, since these cities are not mentioned in the present database, and it will show no bus available for these cities, please update the database too @arijitghosal03

**Comment by Pranjal360Agarwal** [comment]
Update the database and then raise the PR again

**Comment by arijitghosal03** [comment]
@Pranjal360Agarwal I have added the cities to the dropdown menu which are present in the database
image

**Comment by Pranjal360Agarwal** [comment]
is the database working when choose any of the cities from mentioned drop?
i.e is it showing any availbale buses at this page?

**Comment by Pranjal360Agarwal** [comment]
No responses

**Pull request closed without merging**
