### PR TITLE
[GSSoC 23'] Fixed the code corrected the error of file paths

### PR DESCRIPTION
**Pull request by HartzFrequency**
### Reference issue
[Issue No: 193](https://github.com/Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System/issues/193)

### Description 

The bug stems from the reorganized projects, where specific program features interact with a text file. This necessitates fixing the file paths used in various locations is completed.
To ensure the proper functioning of the projects, all instances of file paths are corrected.

### About The Correction

- The entire set of database items and files has been relocated to a distinct directory.
- The paths to the file, which are referenced in various sections and modules of the code, have been recalibrated.

### CODE REVIEW

**Comment by HartzFrequency** [comment]
hello @Pranjal360Agarwal Please check this now I started from the start 🥹

**Comment by HartzFrequency** [comment]
image
image
image
image

**Comment by HartzFrequency** [comment]
@Pranjal360Agarwal please check this now

**Comment by HartzFrequency** [comment]
@Pranjal360Agarwal please check the PR

**Comment by Pranjal360Agarwal** [comment]
> @Pranjal360Agarwal please check the PR

Traceback (most recent call last):
  File "C:\Users\91945\OneDrive\Desktop\ApnaBharat-Bus-Booking-Reservation-System\Bus_booking_system\main.py", line 17, in <module>
    Check = SignIn.Login().mainloop()
  File "C:\Users\91945\OneDrive\Desktop\ApnaBharat-Bus-Booking-Reservation-System\Bus_booking_system\Database\Modules\SignIn_Module\SignIn_page.py", line 47, in __init__
    Image.open("Bus_booking_system\Database\Image\Background_gradient.jpg"),
  File "C:\Users\91945\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 3131, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'Bus_booking_system\\Database\\Image\\Background_gradient.jpg'

**Pull request closed without merging**
