### PR TITLE
Updating Final.py :: reviewing possible Security issues (SQL string injection) and custom Refactoring && Updating ContributorsList.js

### PR DESCRIPTION
**Pull request by Sapt-pal**
Updates to  **Massive scope of refactoring and improving security standards in Final.py #16** [Issue #16 ](https://github.com/Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System/issues/16)

Update to [ContributorsList.js](https://github.com/Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System/blob/master/ContributorsList.js) #5

### CODE REVIEW

**Comment by Pranjal360Agarwal** [comment]
Good work!!
@Sapt-pal 
Starred the project so that I can merged it.

**Comment by Sapt-pal** [comment]
@Pranjal360Agarwal 
Thanks! Looking forward to work more on the issue alongside discovering more issues.
Please do check whether the PR is ready to be merged.

**Comment by Sapt-pal** [comment]
@Pranjal360Agarwal Do confirm whether the conflicts have been resolved or not?

**Comment by Sapt-pal** [comment]
no conflicts as on 20:45 12/11/22

**Comment by Pranjal360Agarwal** [comment]
gr8 work done

**Comment by Sapt-pal** [comment]
> 

Thanks!

**Comment by Pranjal360Agarwal** [comment]
@Sapt-pal check whther the porject is working or not as it showing some errors about missing brackets.... etc.

**Comment by Sapt-pal** [comment]
I am checking immediately.

**Comment by Sapt-pal** [comment]
@Pranjal360Agarwal My apologies, I missed this unmatched bracket error in line 362,
but there should not be any syntactical error as I have setup automatic checks in GitHub for code quality and review.
Will surely take care in future.

**Pull request merged**
