### PR TITLE
Added README-hindi.md and updated README.md

### PR DESCRIPTION
**Pull request by A91y**
README-hindi is added to help multilinguals to read the README easily in their own language and it's link is referred in main README.md to facilitate navigation.
Hence solving issue #60

### CODE REVIEW

**Comment by Pranjal360Agarwal** [comment]
edit the link just above the "open source programs " so that it cannot interfere with the process of raising pr

**Comment by A91y** [comment]
@Pranjal360Agarwal I cannot understand the problem, please eloborate

**Comment by Pranjal360Agarwal** [comment]
edit it one line 167

**Comment by A91y** [comment]
Is everything OK now ?

**Pull request merged**
