### PR TITLE
[GSSoC 23'] Corrected the error caused by incorrectly arranging files in the directory.

### PR DESCRIPTION
**Pull request by HartzFrequency**
### Reference issue
[Issue No: 193](https://github.com/Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System/issues/193)

### Description 

The bug stems from the reorganized projects, where specific program features interact with a text file. This necessitates fixing the file paths used in various locations is completed.
To ensure the proper functioning of the projects, all instances of file paths are corrected.

### About The Correction

- The entire set of database items and files has been relocated to a distinct directory.
- The paths to the file, which are referenced in various sections and modules of the code, have been recalibrated.

### CODE REVIEW

**Comment by HartzFrequency** [comment]
hey @Pranjal360Agarwal please check the PR

**Comment by Pranjal360Agarwal** [comment]
> hey @Pranjal360Agarwal please check the PR

sure

**Comment by Pranjal360Agarwal** [comment]
@HartzFrequency it is still giving same error

**Comment by Pranjal360Agarwal** [comment]
@HartzFrequency according to me - just fresh clone the current repo, make a new program for user dashboard and then amend it.

**Comment by HartzFrequency** [comment]
> @HartzFrequency according to me - just fresh clone the current repo, make a new program for user dashboard and then amend it.

Okay, but this PR is not for User Dashboard actually @Pranjal360Agarwal in the earlier PR someone has rearranged the whole program like creating new directory, moving Image from one folder to another
      which actually screwed up the program and it isn't running so I moved all tha data component to new folder and then gave the path to main.py
      The error shows that Image path of the background image of logging page isn't working which is due to this image movement to different folder by someone in earlier PR.
      If you don't mind can you please clone my forked PR and run the program if it not run I'll try something else

**Comment by Pranjal360Agarwal** [comment]
@HartzFrequency Yes I have already tried it but still the error persists.

**Pull request closed without merging**
