### PR TITLE
Changed Date Entry to Calender

### PR DESCRIPTION
**Pull request by YashGovil**
HI, I've replaced Date Entry to calendar in journey date of set booking so that user will have better experience.
image

### CODE REVIEW

**Comment by Pranjal360Agarwal** [comment]
@YashGovil check whether the project is working or not, it seems no module name tkcalender

**Comment by YashGovil** [comment]
Hi, you need to install tkcalendar using pip and it'll work.
cmd command - pip install tkcalendar

**Comment by Pranjal360Agarwal** [comment]
Yeah I later noticed

**Comment by Pranjal360Agarwal** [comment]
@YashGovil change the date format as it is not aligning as mentioned :- likie in calendar it mm-dd-yyyy and not dd-mm-yyyy

**Comment by YashGovil** [comment]
So we need the date in 'mm-dd-yyyy' format?

**Comment by Pranjal360Agarwal** [comment]
yes

**Comment by Pranjal360Agarwal** [comment]
or you can change the instructions of date to be displayed to your own format

**Pull request merged**
