### PR TITLE
Workflow and aim of project

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Hello sir , I have added Workflow for our Project and Aim behind the project

### CODE REVIEW

**Comment by Pranjal360Agarwal** [comment]
Great Work done @Bharadwajshivam28

**Comment by Bharadwajshivam28** [comment]
thanks sir

**Comment by Bharadwajshivam28** [comment]
sir close the issue so i get point

**Comment by Bharadwajshivam28** [comment]
@Pranjal360Agarwal

**Comment by Bharadwajshivam28** [comment]
sir add iwoc tag with difficulty and close the pr sir @Pranjal360Agarwal

**Comment by Bharadwajshivam28** [comment]
@Pranjal360Agarwal And also assign me sir i guess you have not assigned

**Comment by Bharadwajshivam28** [comment]
add iwoc and diff tag also sir and clsoe it

**Comment by Bharadwajshivam28** [comment]
so i get point

**Comment by Pranjal360Agarwal** [comment]
done

**Comment by Bharadwajshivam28** [comment]
sit this one

**Comment by Pranjal360Agarwal** [comment]
Starred the project @Bharadwajshivam28

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by Bharadwajshivam28** [comment]
close the issue sir i have stared the project

**Comment by Pranjal360Agarwal** [comment]
One question like is your leetcode repo is updating with the questions you solved

**Comment by Pranjal360Agarwal** [comment]
Mine is not updating

**Comment by Bharadwajshivam28** [comment]
> One question like is your leetcode repo is updating with the questions you solved

no sir it is not working

**Comment by Bharadwajshivam28** [comment]
I am doing from leethub extension

**Comment by Bharadwajshivam28** [comment]
but it is not getting updated

**Comment by Bharadwajshivam28** [comment]
sir if you have open source community then please drop links here sir i am die hard open sorce lover or if you have groups of open sorce projects and all

**Comment by Pranjal360Agarwal** [comment]
yes same in my case using leethub it is not working properly

**Comment by Bharadwajshivam28** [comment]
at last please close this issue sir so i get my point

**Comment by Pranjal360Agarwal** [comment]
yes I have a group on discord where you can join to get more info about open source

**Comment by Bharadwajshivam28** [comment]
ye sir please give me links

**Comment by Bharadwajshivam28** [comment]
i love to contibute in open sorce

**Comment by Pranjal360Agarwal** [comment]
https://discord.gg/vEsdETjv

**Comment by Bharadwajshivam28** [comment]
thanks sir

**Comment by Bharadwajshivam28** [comment]
and please close issue sir

**Comment by Bharadwajshivam28** [comment]
> yes I have a group on discord where you can join to get more info about open source

yes

**Comment by Pranjal360Agarwal** [comment]
You can connect with me on linkedin if you want

**Comment by Bharadwajshivam28** [comment]
> You can connect with me on linkedin if you want

yes sir sure drop your id

**Comment by Bharadwajshivam28** [comment]
and please keep me also sir if any open sorce project or event comes

**Comment by Pranjal360Agarwal** [comment]
https://www.linkedin.com/in/pranjal-agarwal-11b543226/

**Comment by Bharadwajshivam28** [comment]
sir can i dm you on discord drop the links there sir from here it is not opening

**Comment by Bharadwajshivam28** [comment]
sir can i dm you on discord drop the links there sir from here it is not opening

**Comment by Bharadwajshivam28** [comment]
PLease close the issue sir

**Comment by Pranjal360Agarwal** [comment]
@Bharadwajshivam28 already closed check it again

**Comment by Bharadwajshivam28** [comment]
> > sir can i dm you on discord drop the links there sir from here it is not opening
> 
> check linkedin dm

ok sir

**Pull request merged**
