### PR TITLE
[Directory Refactoring] Migration to Module

### LINKED ISSUE #131: Migrate the Entire Codebase to a Python Module
## Issues : 
The folder or directory structuring for the project is not organized properly.

## FIX : 
-  A serious migration and proper structuring of the project is needed.
-  Need to use ```.gitignore``` to ignore some basic static files
-  Add a separate ``src`` directory for the frontend. Backend Directories should be separate.
-  There's also no `requirement.txt` for the proper installation of the **modules & packages**, the user has to manually install all the required packages to get the project working.
-  Assets should be kept separate in a public directory.

Would be glad if you assign these issues to me under **GSSoC '2023**.  @Pranjal360Agarwal

### PR DESCRIPTION
**Pull request by pooranjoyb**
# Description
With this PR merged, the entire project is will be migrated to **Python Module**

## Workflow
- [x] Add a separate ``bus-booking-system`` directory for the module. 
- [x] Created `assets` directory that contains `Presentations` & `images`
- [x] Kept the `.html` files in the `web` directory inside the **module**
- [x] Made sure that project starts with `python -m bus-booking-system`

Would be glad if you'd merge this PR @Pranjal360Agarwal  😃 👍

### CODE REVIEW

**Comment by Pranjal360Agarwal** [comment]
@pooranjoyb the project is not working with the changes you have made.

It is important to check whether the core project is working or not before raising the PR, when I go seat booking it is not showing the option to book the seat, no data selecting option.

I have mentored various projects, and I always review the changes and make sure the project is in working condition.
I just do not merge any PR, by looking at fancy things.

I am closing this PR since it is not acceptable from any contributor side, it is my last warning

Structuring is something but working on the project is more important!!

**Comment by pooranjoyb** [comment]
Okay, so this is the thing, you ask me to work on something, I do work on that, and you close the PR without even requesting for changes. 

I don't contribute unnecessarily for the sake of contributions; I do work for what I love to. I saw you project is quite good, but the structuring is totally messed up. So, I raised an issue to fix that. And this is how you publicly respond to someone's work.

If I raise a PR, you can always ask for a review and request the changes. It is not like you'll blame me for some issues by saying stuffs like fancy things and all. **That is purely unprofessional and obviously not expected from mentors**. 

- Your `.py` files were scattered across the directory for no reason. 
- I don't see a reason where the `.html` file has been used. 
- There are some files not linked with the `main.py` files, I don't know why.

The reason is that you **neither you have written a proper documentation of how the project is working nor how it supposed to work**. There are some random `.txt` files across the directory without even mentioning why they exist.

This is not how you work as a mentor, obviously not by talking this rude.
And you talk about warning, well, how many times have you guided me through? If you don't want someone to work on something, then don't ask them to. And if someone's doing something, you could atleast show some respect. @Pranjal360Agarwal

**Comment by Pranjal360Agarwal** [comment]
@pooranjoyb Okay, I totally understand.
I always have respect for your work, I have gone through all of your work, and I note that it takes time for the proper structure of any project.
For words, yeah I agree maybe I should not go through this way.
Or at least I should give suggestions to guide.

On bus booking page, might be there are some files which are not properly linked, you can just recheck it and I assure for your efforts, it will have of Level-3 double from this.

**Comment by pooranjoyb** [comment]
Please check the Working Video & lemme know if some changes are to be made.

[Video-Tue-May-30-2023-13-44-44.webm](https://github.com/Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System/assets/90945182/8734b625-dc33-4c1b-b27a-9cc666e06d75)

@Pranjal360Agarwal

**Pull request merged**
