### PR TITLE
Updated ContributorsList.js file

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Completed it

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
@Pranjal360Agarwal done with it sir

**Comment by Pranjal360Agarwal** [comment]
> @Pranjal360Agarwal done with it sir

Star the repo before it can be merged

**Comment by Bharadwajshivam28** [comment]
ok sir @Pranjal360Agarwal

**Comment by Bharadwajshivam28** [comment]
done sir @Pranjal360Agarwal

**Comment by Bharadwajshivam28** [comment]
@Pranjal360Agarwal sir can you close the issue so that my point get added in IWOC or else I will not get points of not closed so for a time close sir than you can open it after some time

**Comment by Bharadwajshivam28** [comment]
@Pranjal360Agarwal or else I will not get point sir 🙏

**Pull request merged**
