### PR TITLE
[GSSoC 23'] Fixed the file paths error

### PR DESCRIPTION
**Pull request by HartzFrequency**
### Reference issue
[Issue No: 193](https://github.com/Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System/issues/193)

### Description 

The bug stems from the reorganized projects, where specific program features interact with a text file. This necessitates fixing the file paths used in various locations is completed.
To ensure the proper functioning of the projects, all instances of file paths are corrected.

### About The Correction

- The entire set of database items and files has been relocated to a distinct directory.
- The paths to the file, which are referenced in various sections and modules of the code, have been recalibrated.

### CODE REVIEW

**Comment by Pranjal360Agarwal** [comment]
@HartzFrequency review your PR again , as it is giving error:- 

raceback (most recent call last):
  File "C:\Users\91945\OneDrive\Desktop\Folders\ApnaBharat-Bus-Booking-Reservation-System\bus-booking-system\main.py", line 17, in <module>
    Check = SignIn.Login().mainloop()
  File "C:\Users\91945\OneDrive\Desktop\Folders\ApnaBharat-Bus-Booking-Reservation-System\bus-booking-system\Database\Modules\SignIn_Module\SignIn_page.py", line 37, in __init__
    self.bg_image = customtkinter.CTkImage(Image.open("bus-booking-system\Database\Image\Background_gradient.jpg"),size=(self.width, self.height))
  File "C:\Users\91945\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 3131, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'bus-booking-system\\Database\\Image\\Background_gradient.jpg'

**Comment by HartzFrequency** [comment]
Hey @Pranjal360Agarwal please merge this PR!! So that I can raise further PR for next issues

**Comment by Pranjal360Agarwal** [comment]
@HartzFrequency but the the project after merging this PR is not working correctly!!
Correct the issues with this PR, I will merge it.

**Comment by HartzFrequency** [comment]
Hey @Pranjal360Agarwal, 

I've reviewed the PR, and I wanted to clarify something. I've made changes to the file paths in the program, so I'd like to know if you're running the entire program or just the main code. The main code now includes the updated paths, and the error message indicates that the path for the sign-in image is incorrect.
Additionally, could you please check out Discord? I've made updates to the directory hierarchy there.

If the problem continues to persist, I will submit the PR again. Just let me now 

Thank you!!

**Comment by HartzFrequency** [comment]
hey @Pranjal360Agarwal Please check the PR now I have renamed the paths according to python standards

**Comment by Pranjal360Agarwal** [comment]
@HartzFrequency  fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'bus_booking_system\\Database\\Image\\Background_gradient.jpg'  correct this error

**Comment by HartzFrequency** [comment]
> @HartzFrequency  fp = builtins.open(filename, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: 'bus_booking_system\\Database\\Image\\Background_gradient.jpg'  correct this error
> 

Hey @Pranjal360Agarwal ,  
I've reviewed the PR, and I wanted to clarify something. I've made changes to the file paths in the program, so I wanted to know if you're running the entire program or just the main code. 
The main code now includes the updated paths, and the error message indicates that the path for the signIn image is incorrect.
Additionally, could you please check out the Discord? I've made updates to the directory hierarchy there.

If the problem continues to persist, I will submit the PR again. Just let me know
Thank you

**Pull request closed without merging**
